### ISSUE TITLE
word2vec输出结果格式

### ISSUE THREAD

**Issue by superclocks** [koth/kcws#1]
hi, 我看word2vec这一步没有脚本，自己写算的话，输出的结果vec.txt中，是每个词语对应一个向量吗

**Comment by koth** [comment]
是word2vec原生输出的，注意--binary 0 选项
稍后把word2vec代码放第三方目录里

**Comment by zhongkeli** [comment]
能分享vec.txt吗

**Comment by koth** [comment]
更新了下对应说明 也上传了个训练好的vec.txt
