### ISSUE TITLE
中文分词最后一步一定要给它自定义词典吗？可不可以直接用训练出来的word_vocab.txt

### ISSUE THREAD

**Issue by kinghuangdd** [koth/kcws#100]
./bazel-bin/kcws/cc/seg_backend_api --model_path=kcws/models/seg_model.pbtxt(绝对路径到seg_model.pbtxt>) --vocab_path=kcws/models/basic_vocab.txt --max_sentence_len=80
这一步一定要给用户自定义词典吗

**Comment by chiangchiuti** [comment]
自定義辭典不一定要加, 辭典是拿來校正分詞結果的
在viterbi decode 之前調整每個字tag 的權重來達成
