### ISSUE TITLE
调用test_seg.cc文件  发现好多字不识别  比如综合的‘综’，就报错，是里面的utf8to16的原因？还是和我外挂的自定义词典有关系

### ISSUE THREAD

**Issue by kinghuangdd** [koth/kcws#101]
调用test_seg.cc文件  发现好多字不识别  比如综合的‘综’，就报错，是里面的utf8to16的原因？还是和我外挂的自定义词典有关系

**Comment by jarwin123** [comment]
![default](https://user-images.githubusercontent.com/8475971/33213079-ec5e89ba-d160-11e7-9c6c-8a93404f5cc9.png)

**Comment by jarwin123** [comment]
綜合大厦

**Comment by koth** [comment]
看你这个是训练的时候用的词表和在线inference的词表不一致
