### ISSUE TITLE
bazel build kcws/train:generate_training 运行到这一步出错， 求大神帮忙看看

### ISSUE THREAD

**Issue by Xinyi7** [koth/kcws#104]
/Users/jiangxinyi/Downloads/kcws-master/kcws/train/BUILD:2:1: Converting to Python 3: kcws/train/generate_training.py failed: 2to3 failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/python/2to3 --no-diffs --nobackups --write --output-dir bazel-out/local-py3-fastbuild/genfiles/python3/kcws/train --write-unchanged-files ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //kcws/train:generate_training failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by koth** [comment]
目前仅支持python2.7
