### ISSUE TITLE
分词效率低的问题

### ISSUE THREAD

**Issue by Silencezjl** [koth/kcws#110]
最后C++的接口，分词速度很慢。
是不是没调用GPU的原因。

**Comment by koth** [comment]
用的idcnn模型吗？idccn会比bilstm快，效果差不多。另外就是尽量批量分词

**Comment by Silencezjl** [comment]
idcnn模型 会比 bilstm模型快一倍。
但是idcnn模型还是比传统分词模型慢10倍以上。
所以我想在最后C++的接口启用GPU，我看您原来用的是单核CPU吧？
@koth

**Comment by brainbpe** [comment]
同问，我也想知道如何启动gpu加速？  求大神支招 @konth

**Comment by Silencezjl** [comment]
`bazel build --config=opt --config=cuda //kcws/cc:seg_backend_api`
@beyond-boy  理论上，上面这段代码就可以启用GPU了。但是， @koth 精简了 tensorflow 的代码，代码缺少了 cuda 的部分，目前无法启用GPU。

**Comment by koth** [comment]
@Silencezjl  是的，绑定CUDA的话可能会要求cuda驱动版本，cudnn版本一致
最主要是你一次分词用GPU不会带来速度多大改变的， 还不如你每次分词调用的文本多点，这样会有充分利用多核的

**Comment by Silencezjl** [comment]
@koth 有道理，感谢🙏
