### ISSUE TITLE
运行最后一步，报错Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'dilations'

### ISSUE THREAD

**Issue by AlleyEli** [koth/kcws#119]
有大神遇到过这个问题吗？
现在环境 **ubuntu16.04 + bazel0.45 + python2.7.5 + tf1.6.0**
![1](https://user-images.githubusercontent.com/38367699/39682804-a398e00e-51e4-11e8-87bd-e41e24eb2df1.png)

**Comment by AlleyEli** [comment]
版本兼容问题!

**Comment by chmaojian** [comment]
您好，我也遇到同样的问题，请问您是怎么处理de？
我的是Ubuntu18.04+python3.6.9+bazel0.4.5+tensorflow 1.5.1
