### ISSUE TITLE
python kcws/train/filter_sentence.py all.txt （得到train.txt , test.txt)

### ISSUE THREAD

**Issue by busyfree** [koth/kcws#13]
请问，这步执行得到的 train.txt 和 test.txt 是空的文件吗？

**Comment by busyfree** [comment]
新的问题
![image](https://cloud.githubusercontent.com/assets/504251/20747574/85e8ce1c-b725-11e6-8e9d-9cff79353685.png)

**Comment by koth** [comment]
需要按照说明一步一步来

**Comment by busyfree** [comment]
前面的步骤都做了，这个是最后一步了

**Comment by koth** [comment]
vec.txt没生成，或者你之前生成的不叫这个名字

**Comment by busyfree** [comment]
知道问题了，应该是没做 `使用word2vec 训练 chars_for_w2v (注意-binary 0),得到字嵌入结果vec.txt` ，谢谢帮忙找问题

**Comment by busyfree** [comment]
请问作者，word2vec 这个安装包是用python 版本的还是 google的版本？🙏

**Comment by GuangChen2016** [comment]
@koth @busyfree 请问一下 你们是在centos装的bazel吗？我在centos上装完bazel后一直ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package 'external': 
我的tensorflow是通过anaconda装的。有没有办法不用装bazel？谢谢啦

**Comment by busyfree** [comment]
@GuangChen2016 你这个应该是网络问题，开个代理装bazel

**Comment by busyfree** [comment]
@koth  vec.txt 这个是文件是  `./bazel-bin/third_party/word2vec/word2vec -train chars_for_w2v.txt -output kcws/models/vec.txt -size 50 -sample 1e-4 -negative 5 -hs 1 -binary 0 -iter 5` 这个步骤得到的吗？下面是用 前面这个步骤得到的文件执行的结果
![image](https://cloud.githubusercontent.com/assets/504251/20796006/0c2eec10-b80f-11e6-9fc9-614e06feea4a.png)

**Comment by GuangChen2016** [comment]
@busyfree 感觉不像是网络的问题。你的linux是什么系统？装的bazel版本是多少？生成的train.txt是什么样的，能不能共享一下？

**Comment by busyfree** [comment]
@GuangChen2016 centos6.8 x64

**Comment by 2pc** [comment]
@busyfree  upgrader tf version
