### ISSUE TITLE
编译后台服务的命令执行错误

### ISSUE THREAD

**Issue by BiggerHao** [koth/kcws#15]
```
Hao:kcws Hao$ bazel build //kcws/cc:seg_backend_api
WARNING: /private/var/tmp/_bazel_Hao/24147b300412080e7db896e2e916763e/external/org_tensorflow/tensorflow/workspace.bzl:13:5: path_prefix was specified to tf_workspace but is no longer used and will be removed in the future.
WARNING: /private/var/tmp/_bazel_Hao/24147b300412080e7db896e2e916763e/external/org_tensorflow/tensorflow/workspace.bzl:15:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
ERROR: /Users/xxx/kcws/third_party/crow/BUILD:5:1: no such package '@boost//': Error downloading from https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2/download to /private/var/tmp/bazel_Hao/24147b300412080e7db896e2e916763e/external/boost: Error downloading https://sourceforge.net/projects/boost/files/boost/1.61.0/boost1610.tar.bz2/download to /private/var/tmp/bazel_Hao/24147b300412080e7db896e2e916763e/external/boost/download.tar.bz2: Failed to connect to https://superb-sea2.dl.sourceforge.net/project/boost/boost/1.61.0/boost1610.tar.bz2 : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '//third_party/crow:crow'.
ERROR: Analysis of target '//kcws/cc:seg_backend_api' failed; build aborted.
INFO: Elapsed time: 4.937s
```

**Comment by 2pc** [comment]
哈哈，很明显了: Error downloading from https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2/download to /private/var/tmp/bazel_Hao/24147b300412080e7db896e2e916763e/external/boost: Error downloading https://sourceforge.net/projects/boost/files/boost/1.61.0/boost1610.tar.bz2/download to /private/var/tmp/bazel_Hao/24147b300412080e7db896e2e916763e/external/boost/download.tar.bz2: Failed to connect to https://superb-sea2.dl.sourceforge.net/project/boost/boost/1.61.0/boost1610.tar.bz2 : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '//third_party/crow:crow'

不解决网络问题，没啥招，就是不断的执行直到这玩意成功为止，

**Comment by koth** [comment]
我改天传一个boost库放国内吧

**Comment by BiggerHao** [comment]
我在`/private/var/tmp/bazel_Hao/24147b300412080e7db896e2e916763e/external/boost`下面执行`wget https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2`下载好了一个，再去运行`bazel build //kcws/cc:seg_backend_api`就会重新开始下载，不过好在没有继续报错了。
