### ISSUE TITLE
'utf8' codec can't decode bytes in position 0-1: unexpected end of data

### ISSUE THREAD

**Issue by albertyou2** [koth/kcws#20]
@koth  你好我进行到这一步:
./bazel-bin/kcws/train/generate_training vec.txt <语料目录> all.txt
程序报错：
'utf8' codec can't decode bytes in position 0-1: unexpected end of data

请问这个如何解决？

**Comment by koth** [comment]
这个忽略就可以。不用管

**Comment by albertyou2** [comment]
@koth 多谢回复！
我一开始也是忽略这个错误。检查all.txt 文件 ，有279M。

但是我发现，进行下一步：
python kcws/train/filter_sentence.py all.txt

输出LOG：

got bad:872345

然后我去检查 train.txt  tes.txt文件，里面都是空的。
