### ISSUE TITLE
请问公司名识别，语料改如何准备?

### ISSUE THREAD

**Issue by dengzz** [koth/kcws#28]
请问公司名识别，语料改如何准备?

**Comment by koth** [comment]
贴一个标注的样例:

东莞		LOC
明利		NAME
钢材制品	IND
有限公司	ORG

东莞市		LOC
帝达肯		NAME
电子		IND
有限公司	ORG

固力		NAME
保安制品	IND
有限公司	ORG

**Comment by weisong82** [comment]
能否把demo里面的贡献一下 @koth
