### ISSUE TITLE
关于默认分词的效果

### ISSUE THREAD

**Issue by dengzz** [koth/kcws#32]
我按照说明操作后，分词的效果如下。分词效果不是很准，下面是分词结果，这个正常吗？
{
	"msg": "OK",
	"segments": [
		"赵雅",
		"淇",
		"洒泪",
		"道",
		"歉",
		" ",
		"和林",
		"丹",
		"没",
		"有",
		"任",
		"何",
		"经济",
		"关",
		"系" 
	],
	"status": 0 
}

**Comment by koth** [comment]
这个是不正常的，仔细检查下词典之类的

**Comment by lishouguang** [comment]
我也有类似的问题，[自己训练的跟官方的分词不一致](https://github.com/koth/kcws/issues/23)，挺长时间了，没人反馈。

训练过好几次，都是这样。训练步骤也是按照官方说明来的。

**Comment by dengzz** [comment]
关于这个问题，我估计跟词库有关系。kcws是支持自定义词库的。

**Comment by koth** [comment]
文档稍后更新下，关于导出模型，看来大家都不清楚

**Comment by koth** [comment]
更新了文档，自己训练后需要导出下自己的模型文件
