### ISSUE TITLE
F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.

### ISSUE THREAD

**Issue by weisong82** [koth/kcws#33]
root@nlpDemo:/mnt/kcws# export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.1-cp27-none-linux_x86_64.whl
root@nlpDemo:/mnt/kcws# pip install --upgrade $TF_BINARY_URL

通过这种安装的tensorflow，可以运行的。 但是这个项目启动会抛这个错误

**Comment by koth** [comment]
这个warning是不是可以不用去管它？还是不能忽略直接退出了？

**Comment by weisong82** [comment]
无法忽略，直接会退出的。

**Comment by weisong82** [comment]
egg pain.. 折腾一下午，下载源码编译安装的，结果到这边还是报这个错误。。

**Comment by koth** [comment]
@weisong82 OK，这个明天打包个新版本就可以了，知道什么问题了，我之前以为会忽略的，高估了。。。

**Comment by koth** [comment]
换了个包 没事了

**Comment by weisong82** [comment]
ok了！多谢。
