### ISSUE TITLE
tf0.12环境下tf.contrib.rnn.LSTMCell和tf.concat的问题

### ISSUE THREAD

**Issue by crownpku** [koth/kcws#36]
自己的环境是tf0.12，在/kcws/train/train_cws_lstm.py中：

tf.contrib.rnn.LSTMCell(self.numHidden)会报错，要换成tf.nn.rnn_cell.LSTMCell(self.numHidden)

output = tf.concat([forward_output, backward_output], 2)
会报错，要换成
output = tf.concat(2, [forward_output, backward_output])

可能是tensorflow版本的问题。

**Comment by koth** [comment]
对，我升级到1.0.0alpha了
1.0.0应该接口会稳定

**Comment by crownpku** [comment]
（目前本项目需要tf 1.0.0alpha版本以上)
哦哦，漏看了这一句:P
