### ISSUE TITLE
运行web service时出错: tfmodel.cc:87 Session was not created with a graph before Run()!

### ISSUE THREAD

**Issue by crownpku** [koth/kcws#38]
依照readme成功跑完之前的步骤，在最后一步运行web service的时候报错：

I0207 10:51:45.643787   386 tfmodel.cc:64] Reading file to proto: kcws/models/seg_model.pbtxt
I0207 10:51:45.648360   386 tfmodel.cc:69] Creating session.
I0207 10:51:45.675081   386 tfmodel.cc:77] Tensorflow graph loaded from: kcws/models/seg_model.pbtxt
I kcws/cc/tf_seg_model.cc:236] Reading from layer transitions
I kcws/cc/tf_seg_model.cc:242] got num tag:4
I kcws/cc/tf_seg_model.cc:255] Total word :5860
I0207 10:51:45.694744   386 tfmodel.cc:64] Reading file to proto: kcws/models/pos_model.pbtxt
I0207 10:51:45.694774   386 tfmodel.cc:69] Creating session.
I0207 10:51:45.694783   386 tfmodel.cc:77] Tensorflow graph loaded from: kcws/models/pos_model.pbtxt
E0207 10:51:46.211813   386 tfmodel.cc:87] Error during inference: Invalid argument: Session was not created with a graph before Run()!
E kcws/cc/pos_tagger.cc:215] Error during get trans tensors: 
F0207 10:51:46.211869   386 seg_backend_api.cc:57] Check failed: tagger->LoadModel(FLAGS_pos_model_path, FLAGS_word_vocab_path, FLAGS_vocab_path, FLAGS_pos_vocab_path, FLAGS_max_word_num) load pos model error
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by koth** [comment]
更新了下说明，词性标注模型较大，78M，不好放在git上，单独说明了下载
