### ISSUE TITLE
使用用户词库后，特定词"蓝瘦2香菇"分词异常

### ISSUE THREAD

**Issue by dengzz** [koth/kcws#48]
按照说明准备了用户词库文件，里面只包含了一个词条“蓝瘦香菇	4”。
然后使用命令加载用户词库：
./bazel-bin/kcws/cc/seg_backend_api --model_path=kcws/models/seg_model.pbtxt --vocab_path=kcws/models/basic_vocab.txt --user_dict_path=user_dict.txt --max_sentence_len=80
发现，使用“蓝瘦香菇”可以正常分词，而输入“蓝瘦2香菇”时，分词服务出现异常并退出。提示“Segmentation fault (core dumped)”错误。
如果不加载用户词库则正常。

**Comment by koth** [comment]
无法重现。。
