### ISSUE TITLE
embedding_size  AssertionError

### ISSUE THREAD

**Issue by rockyzhengwu** [koth/kcws#5]
在最后train的时候：也就是运行：
python kcws/train/train_cws_lstm.py --word2vec_path vec.txt --train_data_path <绝对路径到train.txt> --test_data_path test.txt --max_sentence_len 80 --learning_rate 0.001

报错：
Traceback (most recent call last):
  File "kcws/train/train_cws_lstm.py", line 262, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "kcws/train/train_cws_lstm.py", line 228, in main
    FLAGS.word2vec_path, FLAGS.num_hidden)
  File "kcws/train/train_cws_lstm.py", line 62, in __init__
    self.c2v = self.load_w2v(c2vPath)
  File "kcws/train/train_cws_lstm.py", line 132, in load_w2v
    assert (dim == (FLAGS.embedding_size))
AssertionError

然后修改了：train_cws_lstm.py 的
`tf.app.flags.DEFINE_integer("embedding_size", 50, "embedding size")`
成
`tf.app.flags.DEFINE_integer("embedding_size", 200, "embedding size")
`就好

**Comment by walkingluo** [comment]
谢谢你哟！
我在执行：
./bazel-bin/kcws/train/generate_training vec.txt <语料目录> all.txt
超过字嵌入维度会报错误：
'utf8' codec can't decode bytes in position 0-1: unexpected end of data
我以为出问题了！

**Comment by rockyzhengwu** [comment]
哦，好像是我搞错了，我在word2vec 输出200的向量，所以需要改。

**Comment by rockyzhengwu** [comment]
'utf8' codec can't decode bytes in position 0-1: unexpected end of data
这个我直接忽略了

**Comment by rockyzhengwu** [comment]
[我的笔记](http://midday.me/article/7935dd274d2f4dccab783a8ce5aa8577)，如果有误还请告知

**Comment by koth** [comment]
更新了对应说明 谢谢反馈
