### ISSUE TITLE
关于准确率的测试

### ISSUE THREAD

**Issue by oneapmlj** [koth/kcws#52]
大神好，我运行标注部分的程序，最后得到了99.57%的准确率，请问这个是正确的吗？是不是太高了。。。跪求回复

**Comment by koth** [comment]
目前是这个，这个是词级别准确率，有可能是这个词性语料本身就是规则生成的，深度学习几乎完美拟合了该规则而已，有语料的可以试试别的语料上的准确率

**Comment by oneapmlj** [comment]
好的，大神，你太棒了，谢谢大神。
