### ISSUE TITLE
询问问题 

### ISSUE THREAD

**Issue by joyivan** [koth/kcws#53]
当我运行 python kcws/train/train_cws_lstm.py --word2vec_path vec.txt --train_data_path ~/kcws/train.txt --test_data_path test.txt --max_sentence_len 80 --learning_rate 0.001
发生错误 

``I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
load data from: vec.txt
train data path: /home/joyivan/kcws/train.txt
Traceback (most recent call last):
  File "kcws/train/train_cws_lstm.py", line 286, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "kcws/train/train_cws_lstm.py", line 256, in main
    total_loss = model.loss(X, Y)
  File "kcws/train/train_cws_lstm.py", line 137, in loss
    P, sequence_length = self.inference(X)
  File "kcws/train/train_cws_lstm.py", line 104, in inference
    reuse=reuse),
TypeError: __init__() got an unexpected keyword argument 'reuse'

**Comment by koth** [comment]
需要升级到1.1了

**Comment by joyivan** [comment]
@koth 升级tensorflow到1.1 ?

**Comment by koth** [comment]
是的

**Comment by joyivan** [comment]
@koth 哥哥 tensorflow 有1.1 了？ where ?  我早上在mac上搞了一天 还是以上错误 。。  ：）

**Comment by joyivan** [comment]
@koth 请问1.1 咋升啊 我官网上也没找到啊。 我两台机器都用的 pip install tensorflow 安装的

**Comment by joyivan** [comment]
@koth thanks a lot, it works
