### ISSUE TITLE
更改word2vec维度后如何重新训练

### ISSUE THREAD

**Issue by wyx1227** [koth/kcws#54]
我先用默认的配置跑了一次人民日报的语料，然后将word2vec维度改为了150，再次训练时（对应的embedding_size也改为了150），报错说左右维度不等：
![image](https://cloud.githubusercontent.com/assets/10024848/24861409/3b31616e-1e2b-11e7-85d1-de80fd79b5b6.png)
如何清除原先的训练信息？

**Comment by wyx1227** [comment]
@koth k神帮帮忙吧？

**Comment by koth** [comment]
@wyx1227 对应logs目录，对应参数改成150就可以啊

**Comment by wyx1227** [comment]
多谢，刚参考了您POS部分，重新设置了--log_dir，也可以了
