### ISSUE TITLE
关于运行web service

### ISSUE THREAD

**Issue by Silencezjl** [koth/kcws#58]
本人小白，请问一下，您最后一步运行web service是用C++实现的吧？ 有没有直接用python进行分词的接口啊？或者.py文件？或者在训练的过程中有？(小白确实没找到直接进行分词的代码～请您指教)

**Comment by koth** [comment]
没有写python的接口，你可以参考下tf的文档，怎么在python中恢复模型，调用接口

**Comment by Silencezjl** [comment]
谢谢啦，我正在学习！

**Comment by Silencezjl** [comment]
请问一下，我的代码这样应该算是回复了模型了吧？要怎么调用接口呢？
`
import tensorflow as tf

with tf.Graph().as_default():
    output_graph_def = tf.GraphDef()
    output_graph_path = '../models/seg_model.pbtxt'
    with open(output_graph_path, "rb") as f:
        output_graph_def.ParseFromString(f.read())
        _ = tf.import_graph_def(output_graph_def, name="")

    with tf.Session() as sess:
        tf.global_variables_initializer().run()
        input = sess.graph.get_tensor_by_name("input_placeholder:0")
        print(input)
        # res = sess.run({input: "我从小学习计算机"})
        # input_x = sess.graph.get_operations()
        # for item in input_x:
        #     print(item)
`
