### ISSUE TITLE
程序测试部分

### ISSUE THREAD

**Issue by yufengzhixing** [koth/kcws#62]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0526 15:34:44.082958 31544 tfmodel.cc:64] Reading file to proto: kcws/models/seg_model.pbtxt
I0526 15:34:44.084977 31544 tfmodel.cc:69] Creating session.
I0526 15:34:44.097151 31544 tfmodel.cc:77] Tensorflow graph loaded from: kcws/models/seg_model.pbtxt
I kcws/cc/tf_seg_model.cc:236] Reading from layer transitions
I kcws/cc/tf_seg_model.cc:242] got num tag:4
I kcws/cc/tf_seg_model.cc:255] Total word :5689
I0526 15:34:44.107872 31544 tfmodel.cc:64] Reading file to proto: kcws/models/pos_model.pbtxt
I0526 15:34:44.142395 31544 tfmodel.cc:69] Creating session.
I0526 15:34:44.145954 31544 tfmodel.cc:77] Tensorflow graph loaded from: kcws/models/pos_model.pbtxt
I kcws/cc/pos_tagger.cc:218] Reading from layer transitions
I kcws/cc/pos_tagger.cc:224] got num tag:74
(2017-05-26 07:34:44) [INFO    ] Crow/0.1 server is running, local port 9090

上面是调用webservice后显示的结果，然后就没有输出了，请问怎么才能实现最终的分词

**Comment by koth** [comment]
浏览器打开http://localhost:9090有个演示页面
