### ISSUE TITLE
编译后台服务出现新错误。。。

### ISSUE THREAD

**Issue by yufengzhixing** [koth/kcws#69]
您好，执行命令：bazel build //kcws/cc:seg_backend_api 报错如下：

ERROR: /home/di/pycharmProjects/segment/kcws/third_party/gflags/BUILD:5:1: Reassignment of builtin build function 'package_name' not permitted.
ERROR: /home/di/pycharmProjects/segment/kcws/third_party/glog/BUILD:5:1: Reassignment of builtin build function 'package_name' not permitted.
ERROR: /home/di/pycharmProjects/segment/kcws/third_party/gflags/BUILD:41:1: Target '//third_party/gflags:empty.cc' contains an error and its package is in error and referenced by '//third_party/gflags:gflags-cxx'.
ERROR: /home/di/pycharmProjects/segment/kcws/third_party/gflags/BUILD:41:1: Target '//third_party/gflags:include/gflags/gflags_declare.h' contains an error and its package is in error and referenced by '//third_party/gflags:gflags-cxx'.
ERROR: /home/di/pycharmProjects/segment/kcws/third_party/gflags/BUILD:41:1: Target '//third_party/gflags:lib/libgflags.a' contains an error and its package is in error and referenced by '//third_party/gflags:gflags-cxx'.
ERROR: /home/di/pycharmProjects/segment/kcws/third_party/gflags/BUILD:41:1: Target '//third_party/gflags:include/gflags/gflags.h' contains an error and its package is in error and referenced by '//third_party/gflags:gflags-cxx'.
ERROR: /home/di/pycharmProjects/segment/kcws/base/BUILD:3:1: Target '//third_party/gflags:gflags-cxx' contains an error and its package is in error and referenced by '//base:base'.
ERROR: /home/di/pycharmProjects/segment/kcws/base/BUILD:3:1: Target '//third_party/glog:glog-cxx' contains an error and its package is in error and referenced by '//base:base'.
ERROR: Analysis of target '//kcws/cc:seg_backend_api' failed; build aborted.
INFO: Elapsed time: 0.167s

执行命令：bazel build third_party/word2vec:word2vec 能成功bazel,其他的命令如：bazel build kcws/train:generate_training，bazel build kcws/cc:dump_vocab均会类似如上错误。在build文件中加了“licenses(["notice"])”依然不行。。。
请问大神这是是什么原因，有空的话能不能帮看一下，不甚感激！

**Comment by koth** [comment]
你的bazel版本多少，尝试使用bazel 0.4.5+看看

**Comment by yufengzhixing** [comment]
@koth 用的bazel0.5.2 ，会不会是因为某些包需要翻墙啊

**Comment by koth** [comment]
哦，那估计是版本太高了，先降到0.5.0应该可以，或者回头我升级下提交。bazel现在还没稳定版，经常改

**Comment by yufengzhixing** [comment]
@koth 人生处处是bug，果然是bazel的问题，降到0.5.0以后可以正常运行了，非常感谢koth大神。
