### ISSUE TITLE
bazel build third_party/word2vec:word2vec  Error

### ISSUE THREAD

**Issue by tonyatml** [koth/kcws#7]
WARNING: /home/ml/.cache/bazel/_bazel_ml/7e44fa86fc02571bc1e4272504e8778f/external/org_tensorflow/tensorflow/workspace.bzl:13:5: path_prefix was specified to tf_workspace but is no longer used and will be removed in the future.
WARNING: /home/ml/.cache/bazel/_bazel_ml/7e44fa86fc02571bc1e4272504e8778f/external/org_tensorflow/tensorflow/workspace.bzl:15:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
INFO: Found 1 target...
ERROR: /home/ml/py27env/kcws/third_party/word2vec/BUILD:5:1: Linking of rule '//third_party/word2vec:word2vec' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local-fastbuild/bin/third_party/word2vec/word2vec -Wl,-no-as-needed -B/usr/bin -B/usr/bin -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/local-fastbuild/bin/third_party/word2vec/_objs/word2vec/third_party/word2vec/word2vec.pic.o: In function `TrainModel':
word2vec.c:(.text+0x35bd): undefined reference to `pthread_create'
word2vec.c:(.text+0x3600): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
Target //third_party/word2vec:word2vec failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.325s, Critical Path: 0.22s

**Comment by koth** [comment]
修复了build文件
