### ISSUE TITLE
请问tf_dist是对编译依赖项的打包吗？可以确保是和官方版本一致吗？

### ISSUE THREAD

**Issue by npuichigo** [koth/kcws#71]
如果要把整个tensorflow作为third_party的话，有什么方便的办法来写bazel的BUILD呢

**Comment by koth** [comment]
是的，是把tf的静态库重新打包，可以定期跟官方同步。
源码依赖非常繁杂，需要配置很多东西，不推荐这种方式。

**Comment by endymecy** [comment]
静态库如何打包？是手动抽取出来打包的吗？
