### ISSUE TITLE
运行bazel build //kcws/cc:seg_backend_api报错

### ISSUE THREAD

**Issue by MrHello** [koth/kcws#74]
你好，运行如上代码时报错：
ERROR: /Users/user/Downloads/kcws-master/third_party/gflags/BUILD:5:1: Reassignment of builtin build function 'package_name' not permitted.
ERROR: /Users/user/Downloads/kcws-master/third_party/glog/BUILD:5:1: Reassignment of builtin build function 'package_name' not permitted.

**Comment by koth** [comment]
升级/降级 bazel到0.4.5-0.5之间

**Comment by koth** [comment]
已修复
