### ISSUE TITLE
关于模型输出后的分值矩阵如何与viterbi或crf结合转为最终的分词切分

### ISSUE THREAD

**Issue by Alan000** [koth/kcws#75]
作者您好，现有一点不明。就是模型输出后的分值矩阵怎么计算最后的最优切分，有没有相关的介绍文档。我看到最后似乎用到viterbi，是否能有具体一点的说明。

**Comment by koth** [comment]
嗯，是viterbi算法，算法原理什么的可能看wiki或者别的博客会讲得更清楚。
