### ISSUE TITLE
请问 tf_dist_1.2.0_rc1_0604.zip 这个文件是从tensorflow源码编译出来的么?

### ISSUE THREAD

**Issue by omengye** [koth/kcws#78]
请问压缩包下面的 lib/unix 文件夹中 aggregate_ops.o_435.o 等一堆 .o 文件是直接编译的tensorflow源码还是源码中的一部分, 或者是从其他项目编译过来的? 能否详细说明一下? 谢谢

**Comment by koth** [comment]
是直接编译出来的,tensorflow/contrib/makefile/build_all_linux.sh这个可以编译出静态文件

**Comment by omengye** [comment]
@koth 谢谢

**Comment by lsqpku** [comment]
你好,运行bazel build //kcws/cc:seg_backend_api报错：看起来是找不到tensorflow，但是我的机器已经安装了tensorflow 1.1.0，并且一直没出过问题。是必须升级到1.2才行吗？

ERROR: /home/admin/PycharmProjects/kcws/kcws/cc/BUILD:3:1: no such package '@tf//': Error downloading [https://gitlab.com/yovnchine/tfrelates/raw/master/tf_dist_1.2.0_rc1_0604.zip] to /home/admin/.cache/bazel/_bazel_admin/737e9d4cb428f6ecba8b1b5e484b9b1c/external/tf/tf_dist_1.2.0_rc1_0604.zip: Unknown host: gitlab.com and referenced by '//kcws/cc:tf_seg_model'.
ERROR: Analysis of target '//kcws/cc:seg_backend_api' failed; build aborted.
INFO: Elapsed time: 6.775s

**Comment by omengye** [comment]
@lsqpku "Unknown host: gitlab.com", 你这个是无法下载tf_dist_1.2.0_rc1_0604.zip造成的, 作者将自己编译好的tensorflow放在了 https://gitlab.com/yovnchine/tfrelates/blob/master/tf_dist_1.2.0_rc1_0604.zip 上
