### ISSUE TITLE
运行bazel build //kcws/cc:seg_backend_api报错

### ISSUE THREAD

**Issue by lsqpku** [koth/kcws#79]
你好,运行bazel build //kcws/cc:seg_backend_api报错：看起来是找不到tensorflow，但是我的机器已经安装了tensorflow 1.1.0，并且一直没出过问题。是必须升级到1.2才行吗？ 此外还报错找不到boost，但是boost我也安装过。

ERROR: /home/admin/PycharmProjects/kcws/kcws/cc/BUILD:3:1: no such package '@tf//': Error downloading [https://gitlab.com/yovnchine/tfrelates/raw/master/tf_dist_1.2.0_rc1_0604.zip] to /home/admin/.cache/bazel/_bazel_admin/737e9d4cb428f6ecba8b1b5e484b9b1c/external/tf/tf_dist_1.2.0_rc1_0604.zip: Unknown host: gitlab.com and referenced by '//kcws/cc:tf_seg_model'.
ERROR: Analysis of target '//kcws/cc:seg_backend_api' failed; build aborted.
INFO: Elapsed time: 6.775s

**Comment by koth** [comment]
这个是网络访问问题，可以检查下你的网络是否能访问gitlab.com
