### ISSUE TITLE
运行bazel build //kcws/cc:seg_backend_api 报错

### ISSUE THREAD

**Issue by kinghuangdd** [koth/kcws#80]
(tensorflow) kinghuang@kinghuang-virtual-machine:~/anaconda3/envs/kcws-master$ bazel build //kcws/cc:seg_backend_api
.........................
ERROR: /home/kinghuang/anaconda3/envs/kcws-master/third_party/glog/BUILD:5:1: Reassignment of builtin build function 'package_name' not permitted
ERROR: /home/kinghuang/anaconda3/envs/kcws-master/third_party/gflags/BUILD:5:1: Reassignment of builtin build function 'package_name' not permitted
ERROR: /home/kinghuang/anaconda3/envs/kcws-master/third_party/glog/BUILD:13:1: Target '//third_party/glog:glog-0.3.4.tar.gz' contains an error and its package is in error and referenced by '//third_party/glog:glog-srcs'
ERROR: /home/kinghuang/anaconda3/envs/kcws-master/third_party/glog/BUILD:40:1: Target '//third_party/gflags:gflags-cxx' contains an error and its package is in error and referenced by '//third_party/glog:glog-cxx'
ERROR: /home/kinghuang/anaconda3/envs/kcws-master/third_party/glog/BUILD:40:1: Target '//third_party/glog:empty.cc' contains an error and its package is in error and referenced by '//third_party/glog:glog-cxx'
ERROR: /home/kinghuang/anaconda3/envs/kcws-master/third_party/glog/BUILD:40:1: Target '//third_party/glog:include/glog/log_severity.h' contains an error and its package is in error and referenced by '//third_party/glog:glog-cxx'
ERROR: /home/kinghuang/anaconda3/envs/kcws-master/third_party/glog/BUILD:40:1: Target '//third_party/glog:include/glog/raw_logging.h' contains an error and its package is in error and referenced by '//third_party/glog:glog-cxx'
ERROR: /home/kinghuang/anaconda3/envs/kcws-master/third_party/glog/BUILD:40:1: Target '//third_party/glog:include/glog/stl_logging.h' contains an error and its package is in error and referenced by '//third_party/glog:glog-cxx'
ERROR: /home/kinghuang/anaconda3/envs/kcws-master/third_party/glog/BUILD:40:1: Target '//third_party/glog:include/glog/vlog_is_on.h' contains an error and its package is in error and referenced by '//third_party/glog:glog-cxx'
ERROR: /home/kinghuang/anaconda3/envs/kcws-master/third_party/glog/BUILD:40:1: Target '//third_party/glog:lib/libglog.a' contains an error and its package is in error and referenced by '//third_party/glog:glog-cxx'
ERROR: /home/kinghuang/anaconda3/envs/kcws-master/third_party/glog/BUILD:40:1: Target '//third_party/glog:include/glog/logging.h' contains an error and its package is in error and referenced by '//third_party/glog:glog-cxx'
ERROR: /home/kinghuang/anaconda3/envs/kcws-master/base/BUILD:3:1: Target '//third_party/gflags:gflags-cxx' contains an error and its package is in error and referenced by '//base:base'
ERROR: /home/kinghuang/anaconda3/envs/kcws-master/base/BUILD:3:1: Target '//third_party/glog:glog-cxx' contains an error and its package is in error and referenced by '//base:base'
ERROR: Analysis of target '//kcws/cc:seg_backend_api' failed; build aborted
INFO: Elapsed time: 10.810s
FAILED: Build did NOT complete successfully (13 packages loaded)

**Comment by koth** [comment]
bazel版本问题，已修复，现在兼容bazel 0.5+！
