### ISSUE TITLE
加入用户词典后，有时会出现死循环，在doScan函数里

### ISSUE THREAD

**Issue by haofengrushui204** [koth/kcws#81]
求解答

**Comment by koth** [comment]
可以再试试，提交了新代码，如有问题麻烦给出下测试语句

**Comment by haofengrushui204** [comment]
非常感谢，问题已经解决。
之前的例子是：用户词典为[刑事和解，事故责任，责任事故，事先策划]，对于句子"刑事。" 就会陷入死循环。 看代码，问题出在 ac_scanner.h 文件中的
cur = parent->fail_node_;
        // if (parent != root_) {
        //   --i;
        // }
这几行代码，还以为是buildFailNode()的问题呢。
