### ISSUE TITLE
修改了max_word_num 的最大值，运行起来报错

### ISSUE THREAD

**Issue by younger911** [koth/kcws#82]
koth大大，请教个问题，我修改了 seg_backend_api.cc的 DEFINE_int32(max_word_num, 300, "max num of word per sentence ");将值改到了300，我测试的句子里面的字数比较多，在运行时报以下错误：
E0918 11:23:35.434610 26934 tfmodel.cc:88] Error during inference: Invalid argument: Input to reshape is a tensor with 640 values, but the                                requested shape requires a multiple of 1200
         [[Node: Reshape_7 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _output_shapes=[[?,300,4]], _device="/job:localhost/replica:0/task:0/cpu:                               0"](idcnn_1/scores, Reshape_7/shape)]]
2017-09-18 11:23:35.434675: E kcws/cc/tf_seg_model.cc:321] Error during inference:

这种情况是不是我要重新训练models里面的word_vocab.txt文件？还是什么问题呢？如果是word_vocab.txt的问题，这个文本文件怎么训练呢？谢谢解惑.

**Comment by koth** [comment]
因为模型里的place holder是指定的80。你需要更改模型，然后重新训练

**Comment by younger911** [comment]
非常感谢你的解答， seg_backend_api.cc里面的DEFINE_int32(max_sentence_len, 80, "max sentence len ");
DEFINE_int32(max_word_num, 50, "max num of word per sentence ");   80是句子的数量，50是词的数量，place holder是指定的80这个是句子的数量吗？ 模型文件夹里面的basic_vocab.txt  pos_vocab.txt  word_vocab.txt都需要重新训练吗?

**Comment by koth** [comment]
max sentence len 是一个句子最长几个unicode字符
max_word_num是一句最多几个词。
basic_vocab.txt pos_vocab.txt word_vocab.txt一般不需要重新训练

**Comment by younger911** [comment]
非常感谢你的解答,谢谢。 在训练词性标注的这个时 python kcws/train/prepare_pos.py  /e/data/people_2014  pos_lines.txt   /e/data/people_2014是人民网2014的语料吗？

**Comment by koth** [comment]
是的

**Comment by younger911** [comment]
thanks very much!
