### ISSUE TITLE
missing input file '//kcws/cc:scan_reporter.h'.

### ISSUE THREAD

**Issue by SHUlibee** [koth/kcws#83]
您好，我在运行 bazel build //kcws/cc:seg_backend_api 时会报如下错误：
.......................................................
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: missing input file '//kcws/cc:scan_reporter.h'.
ERROR: /home/vagrant/workspace/kcws/kcws/cc/BUILD:166:1: //kcws/cc:ac_scanner: missing input file '//kcws/cc:scan_reporter.h'.
Target //kcws/cc:seg_backend_api failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/vagrant/workspace/kcws/kcws/cc/BUILD:166:1 1 input file(s) do not exist.
INFO: Elapsed time: 418.071s, Critical Path: 0.21s

**Comment by SHUlibee** [comment]
补充下环境版本
Redhat  6.5
python 3.5
bazel 4.5
java 1.8

**Comment by koth** [comment]
已修复

**Comment by SHUlibee** [comment]
@koth 好的，多谢
