### ISSUE TITLE
频繁报错，很崩溃～～已经跑通过的各路大神都用的是什么环境啊？python  tensorlfow

### ISSUE THREAD

**Issue by kinghuangdd** [koth/kcws#86]

**Comment by SHUlibee** [comment]
@kinghuangdd 你用的kcws代码是什么时候拉取的啊？

**Comment by SHUlibee** [comment]
@kinghuangdd 我这边是用anaconda搭建的环境，不过跑这个项目 连 
构建 
3、编译后台服务 
bazel build //kcws/cc:seg_backend_api
这一步都没有过 - -

**Comment by kinghuangdd** [comment]
代码是9月13号拉取的。我一开始用的是anaconda自带的python3.6  tf是1.0版  bazel 5.2版   结果各种坑啊   后来bazel降到了4.5  能把分词跑到最后一步了  可是web service那步过不去。
之后跑词性标注  又是错啊错 各种调试发现 python2.7能跑  可我用的是ubuntu自带的  所以又安装个tensorflow了 没有装anaconda  又是各种错 （之前的anaconda是和python3.6配套的）
现在的情况是python3.7 2.7 我都有  还有ananconda  tf1.3  1.0  比较乱

**Comment by koth** [comment]
bazel 0.5.4+ python2.7 gcc4.9+
