### ISSUE TITLE
大神，bazel build //kcws/cc:seg_backend_api 报错

### ISSUE THREAD

**Issue by maczhao** [koth/kcws#87]
ERROR: /root/kcws/third_party/gflags/BUILD:12:1: Executing genrule //third_party/gflags:gflags-srcs failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 77.

**Comment by maczhao** [comment]
方便建一个微信或者QQ群吗？

**Comment by koth** [comment]
很可能没装cmake,你装个cmake后再看看

**Comment by maczhao** [comment]
Package cmake-2.8.12.2-4.el6.x86_64 already installed and latest version

**Comment by gembin** [comment]
@koth bazel  version 0.7.0,  cmake version 3.9.4,  同样的问题, 怎么解决？
```bash
 bazel build //kcws/cc:seg_backend_api                            
ERROR: /Users/zb/kcws/kcws/cc/BUILD:3:1: no such package '@protobuf//': Error downloading [http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/2b7430d96aeff2bb624c8d52182ff5e4b9f7f18a.tar.gz, https://github.com/google/protobuf/archive/2b7430d96aeff2bb624c8d52182ff5e4b9f7f18a.tar.gz] to /private/var/tmp/_bazel_zb/63f1d599a20b50f95b606a662ec80c73/external/protobuf/2b7430d96aeff2bb624c8d52182ff5e4b9f7f18a.tar.gz: Checksum was 94789497712726816f154f8441ed4319573c78c3f8cc6398bb00f464ffd82bd2 but wanted e5d3d4e227a0f7afb8745df049bbd4d55474b158ca5aaa2a0e31099af24be1d0 and referenced by '//kcws/cc:tf_seg_model'.
ERROR: Analysis of target '//kcws/cc:seg_backend_api' failed; build aborted: no such package '@protobuf//': Error downloading [http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/2b7430d96aeff2bb624c8d52182ff5e4b9f7f18a.tar.gz, https://github.com/google/protobuf/archive/2b7430d96aeff2bb624c8d52182ff5e4b9f7f18a.tar.gz] to /private/var/tmp/_bazel_zb/63f1d599a20b50f95b606a662ec80c73/external/protobuf/2b7430d96aeff2bb624c8d52182ff5e4b9f7f18a.tar.gz: Checksum was 94789497712726816f154f8441ed4319573c78c3f8cc6398bb00f464ffd82bd2 but wanted e5d3d4e227a0f7afb8745df049bbd4d55474b158ca5aaa2a0e31099af24be1d0.
INFO: Elapsed time: 37.302s
```

**Comment by wangsanpeng** [comment]
@gembin  遇到了同样的问题啊，是不是网络问题啊？？解决了没有？

**Comment by gembin** [comment]
@wangsanpeng 没有😓，太费劲。。。先不搞了，这项目3个月没更新了。。。

**Comment by johnsenliu** [comment]
@gembin 同样的问题啊啊啊
`ERROR: /private/var/tmp/_bazel_root/8ec84bee17a4e59692bf3092402c706c/external/protobuf/BUILD:434:1: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_root/8ec84bee17a4e59692bf3092402c706c/external/protobuf/BUILD", line 434
                cc_proto_library(name = "cc_test_protos", srcs = (L...), <4 more arguments>)
        File "/private/var/tmp/_bazel_root/8ec84bee17a4e59692bf3092402c706c/external/protobuf/protobuf.bzl", line 247, in cc_proto_library
                cc_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /private/var/tmp/_bazel_root/8ec84bee17a4e59692bf3092402c706c/external/protobuf/BUILD:728:1: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_root/8ec84bee17a4e59692bf3092402c706c/external/protobuf/BUILD", line 728
                py_proto_library(name = "python_specific_test_pro...", <6 more arguments>)
        File "/private/var/tmp/_bazel_root/8ec84bee17a4e59692bf3092402c706c/external/protobuf/protobuf.bzl", line 373, in py_proto_library
                py_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /private/var/tmp/_bazel_root/8ec84bee17a4e59692bf3092402c706c/external/protobuf/BUILD:113:1: Target '@protobuf//:ios_arm64' contains an error and its package is in error and referenced by '@protobuf//:protobuf'
ERROR: /private/var/tmp/_bazel_root/8ec84bee17a4e59692bf3092402c706c/external/protobuf/BUILD:113:1: Target '@protobuf//:ios_armv7' contains an error and its package is in error and referenced by '@protobuf//:protobuf'
ERROR: /private/var/tmp/_bazel_root/8ec84bee17a4e59692bf3092402c706c/external/protobuf/BUILD:113:1: Target '@protobuf//:ios_armv7s' contains an error and its package is in error and referenced by '@protobuf//:protobuf'
ERROR: /private/var/tmp/_bazel_root/8ec84bee17a4e59692bf3092402c706c/external/protobuf/BUILD:113:1: Target '@protobuf//:android' contains an error and its package is in error and referenced by '@protobuf//:protobuf'
ERROR: /private/var/tmp/_bazel_root/8ec84bee17a4e59692bf3092402c706c/external/tf/BUILD.bazel:24:1: Target '@protobuf//:protobuf' contains an error and its package is in error and referenced by '@tf//:tensorflow'
ERROR: /Users/shuliu/liushu_py3/kcws/kcws/cc/BUILD:22:1: Target '@protobuf//:protobuf' contains an error and its package is in error and referenced by '//kcws/cc:pos_tagger'
ERROR: /Users/shuliu/liushu_py3/kcws/kcws/cc/BUILD:3:1: Target '@protobuf//:protobuf' contains an error and its package is in error and referenced by '//kcws/cc:tf_seg_model'
ERROR: Analysis of target '//kcws/cc:seg_backend_api' failed; build aborted: Loading failed
`

**Comment by johnsenliu** [comment]
@koth 求大神帮助

**Comment by Xinyi7** [comment]
遇到了一样的问题，求大神帮助啊
ERROR: /private/var/tmp/_bazel_jiangxinyi/c4f83c27db6d18a31019acac9a2e6e0e/external/protobuf/BUILD:434:1: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jiangxinyi/c4f83c27db6d18a31019acac9a2e6e0e/external/protobuf/BUILD", line 434
		cc_proto_library(name = "cc_test_protos", srcs = (L...), <4 more arguments>)
	File "/private/var/tmp/_bazel_jiangxinyi/c4f83c27db6d18a31019acac9a2e6e0e/external/protobuf/protobuf.bzl", line 247, in cc_proto_library
		cc_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /private/var/tmp/_bazel_jiangxinyi/c4f83c27db6d18a31019acac9a2e6e0e/external/protobuf/BUILD:728:1: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jiangxinyi/c4f83c27db6d18a31019acac9a2e6e0e/external/protobuf/BUILD", line 728
		py_proto_library(name = "python_specific_test_pro...", <6 more arguments>)
	File "/private/var/tmp/_bazel_jiangxinyi/c4f83c27db6d18a31019acac9a2e6e0e/external/protobuf/protobuf.bzl", line 373, in py_proto_library
		py_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /private/var/tmp/_bazel_jiangxinyi/c4f83c27db6d18a31019acac9a2e6e0e/external/protobuf/BUILD:113:1: Target '@protobuf//:ios_arm64' contains an error and its package is in error and referenced by '@protobuf//:protobuf'
ERROR: /private/var/tmp/_bazel_jiangxinyi/c4f83c27db6d18a31019acac9a2e6e0e/external/protobuf/BUILD:113:1: Target '@protobuf//:ios_armv7' contains an error and its package is in error and referenced by '@protobuf//:protobuf'
ERROR: /private/var/tmp/_bazel_jiangxinyi/c4f83c27db6d18a31019acac9a2e6e0e/external/protobuf/BUILD:113:1: Target '@protobuf//:ios_armv7s' contains an error and its package is in error and referenced by '@protobuf//:protobuf'
ERROR: /private/var/tmp/_bazel_jiangxinyi/c4f83c27db6d18a31019acac9a2e6e0e/external/protobuf/BUILD:113:1: Target '@protobuf//:android' contains an error and its package is in error and referenced by '@protobuf//:protobuf'
ERROR: /Users/jiangxinyi/Downloads/kcws-master/kcws/cc/BUILD:3:1: Target '@protobuf//:protobuf' contains an error and its package is in error and referenced by '//kcws/cc:tf_seg_model'
ERROR: Analysis of target '//kcws/cc:seg_backend_api' failed; build aborted: Loading failed
INFO: Elapsed time: 2.240s

**Comment by koth** [comment]
需要升级bazel到0.5+

**Comment by johnsenliu** [comment]
大佬，我的bazel是0.9.0版，是不是应该降一降级啊

**Comment by koth** [comment]
@johnsenliu 降到0.7应该可以

**Comment by xikunlun001** [comment]
@johnsenliu 你试过降到0.7.0试了了, 我的问题和你的一模一样

**Comment by xikunlun001** [comment]
ERROR: /private/var/tmp/_bazel_xichen/271555ce4d6dd317aab3a86f4399957d/external/protobuf/BUILD:434:1: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_xichen/271555ce4d6dd317aab3a86f4399957d/external/protobuf/BUILD", line 434
		cc_proto_library(name = "cc_test_protos", srcs = (L...), <4 more arguments>)
	File "/private/var/tmp/_bazel_xichen/271555ce4d6dd317aab3a86f4399957d/external/protobuf/protobuf.bzl", line 247, in cc_proto_library
		cc_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /private/var/tmp/_bazel_xichen/271555ce4d6dd317aab3a86f4399957d/external/protobuf/BUILD:728:1: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_xichen/271555ce4d6dd317aab3a86f4399957d/external/protobuf/BUILD", line 728
		py_proto_library(name = "python_specific_test_pro...", <6 more arguments>)
	File "/private/var/tmp/_bazel_xichen/271555ce4d6dd317aab3a86f4399957d/external/protobuf/protobuf.bzl", line 373, in py_proto_library
		py_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /private/var/tmp/_bazel_xichen/271555ce4d6dd317aab3a86f4399957d/external/protobuf/BUILD:113:1: Target '@protobuf//:ios_arm64' contains an error and its package is in error and referenced by '@protobuf//:protobuf'
ERROR: /private/var/tmp/_bazel_xichen/271555ce4d6dd317aab3a86f4399957d/external/protobuf/BUILD:113:1: Target '@protobuf//:ios_armv7' contains an error and its package is in error and referenced by '@protobuf//:protobuf'
ERROR: /private/var/tmp/_bazel_xichen/271555ce4d6dd317aab3a86f4399957d/external/protobuf/BUILD:113:1: Target '@protobuf//:ios_armv7s' contains an error and its package is in error and referenced by '@protobuf//:protobuf'
ERROR: /private/var/tmp/_bazel_xichen/271555ce4d6dd317aab3a86f4399957d/external/protobuf/BUILD:113:1: Target '@protobuf//:android' contains an error and its package is in error and referenced by '@protobuf//:protobuf'
ERROR: /private/var/tmp/_bazel_xichen/271555ce4d6dd317aab3a86f4399957d/external/tf/BUILD.bazel:24:1: Target '@protobuf//:protobuf' contains an error and its package is in error and referenced by '@tf//:tensorflow'
ERROR: /Users/xichen/kcws/kcws/cc/BUILD:22:1: Target '@protobuf//:protobuf' contains an error and its package is in error and referenced by '//kcws/cc:pos_tagger'
ERROR: /Users/xichen/kcws/kcws/cc/BUILD:3:1: Target '@protobuf//:protobuf' contains an error and its package is in error and referenced by '//kcws/cc:tf_seg_model'
ERROR: Analysis of target '//kcws/cc:seg_backend_api' failed; build aborted: Loading failed
INFO: Elapsed time: 148.311s
FAILED: Build did NOT complete successfully (17 packages loaded)

**Comment by xikunlun001** [comment]
@koth 老大能帮我看看不...
