### ISSUE TITLE
undefined symbol: _Py_FalseStruct

### ISSUE THREAD

**Issue by chiangchiuti** [koth/kcws#95]
mldp@ipc-kvm:~/NLP/kcws$ ./bazel-bin/kcws/train/generate_training vec.txt ../2014/  all.txt
Traceback (most recent call last):
  File "/home/mldp/NLP/kcws/bazel-bin/kcws/train/generate_training.runfiles/__main__/kcws/train/generate_training.py", line 9, in <module>
    import w2v
ImportError: /home/mldp/NLP/kcws/bazel-bin/kcws/train/generate_training.runfiles/__main__/utils/w2v.so: undefined symbol: _Py_FalseStruct

---------
After I ran ./bazel-bin/kcws/train/generate_training, I meet the error 'undefined symbol: _Py_FalseStruct'
Anyone here meet the same problem??

Python 3.5.2
tensorflow 1.2.0-rc0

**Comment by koth** [comment]
you can try python2.7 ,python3+ is not supported currently
