### ISSUE TITLE
https://github.com/koth/kcws/blob/master/kcws/train/train_pos.py#L133

### ISSUE THREAD

**Issue by elias-1** [koth/kcws#96]
Why [-1, FLAGS.max_sentence_len,
                                                 FLAGS.embedding_char_size,
                                                 FLAGS.max_chars_per_word]
rather than [-1, FLAGS.max_sentence_len,
                                                 FLAGS.max_chars_per_word,
                                                 FLAGS.embedding_char_size]

**Comment by koth** [comment]
Its a bug,  and I corrected this code now, thanks you.
